name: app_ui
description: "Design System of Music App."
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.3.0
flutter:
